In [26]:
import numpy as np
import sympy as sp

In [14]:
# Slicing and comparing.
A = np.array([[2, 4, 6], [8, 0, 1]])
B = np.array([[-(-2), 16/4, 6], [8, 0, -3/-3]])

print(np.shape(A))
print(A[0][1], A[1][2])
print(np.equal(A, B))

(2, 3)
4 1
[[ True  True  True]
 [ True  True  True]]


In [15]:
# Adittion and substraction.
C = np.array([[1, 8], [11, 4], [0, 9]])
D = np.array([[6, -7], [3, 15], [2, 5]])

print(C + D)
print(C - D)

[[ 7  1]
 [14 19]
 [ 2 14]]
[[ -5  15]
 [  8 -11]
 [ -2   4]]


In [16]:
# Addition, substraction and multiplication.
E = np.array([[-1, 2, 6], [8, -7, 5]])
F = np.array([[-3, -5, -2], [0, 4, 7]])

print((4*A) + (3*B), end='\n\n')
print((5*A) - (2*B), end='\n\n')

[[14. 28. 42.]
 [56.  0.  7.]]

[[ 6. 12. 18.]
 [24.  0.  3.]]



In [17]:
# Transponse.
G = np.array([[2, 0, -1], [4, 6, 8]])
print(np.transpose(G), end='\n\n')
print(G.T, end='\n\n')
# double transponse.
print(G.T.T, end='\n\n')

[[ 2  4]
 [ 0  6]
 [-1  8]]

[[ 2  4]
 [ 0  6]
 [-1  8]]

[[ 2  0 -1]
 [ 4  6  8]]



In [18]:
# 
H = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[7, 8, 9], [10, 11, 12]])

print((H + I).T, end='\n\n')
print((H.T + I.T), end='\n\n')

[[ 8 14]
 [10 16]
 [12 18]]

[[ 8 14]
 [10 16]
 [12 18]]



In [19]:
# Column-row vectors multiplication.
row = np.array([[-2, 4, 6]])
col = np.array([[-3], [-6], [9]])

print(col @ row)

[[  6 -12 -18]
 [ 12 -24 -36]
 [-18  36  54]]


In [20]:
# 3X2, 2X3 multiplication matrix.
J = np.array([[2, 4], [1, 3], [5, 8]])
K = np.array([[0, 6, -1], [1, 7, 11]])

print(J @ K)

[[ 4 40 42]
 [ 3 27 32]
 [ 8 86 83]]


In [21]:
L = np.array([[2, -3, 4], [-7, 8, 1]])
M = np.array([[2, -9], [-4, 5], [7, -8]])
N = np.array([[-6, 3], [5, 7]])

print((L @ M) @ N, end='\n\n')
print(L @ (M @ N), end='\n\n')

[[-589 -323]
 [ 709  548]]

[[-589 -323]
 [ 709  548]]



In [22]:
# Identiy matrix
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
O = np.array([[2, -5, 9], [4, 8, 6]])


I2 = np.identity(2)
I3 = np.identity(3)

print(I2 @ O, end='\n\n')
print(O @ I3, end='\n\n')

[[ 2. -5.  9.]
 [ 4.  8.  6.]]

[[ 2. -5.  9.]
 [ 4.  8.  6.]]



In [24]:
# Equation system solving.
P = np.array([[1,1], [2, 1]])
q = np.array([[5], [7]])


R = np.array([[2, 10, -40], [-4, -7, 41], [1, 3, -12]])
s = np.array([[-4], [-31], [-6]])


print(np.linalg.solve(P, q), end='\n\n')
print(np.linalg.solve(R, s), end='\n\n')

[[2.]
 [3.]]

[[-12.]
 [-18.]
 [ -5.]]



In [32]:
x, y, z, a, b, c = sp.symbols('x y z a b c')

eq1 = sp.Eq(x + y, a)
eq2 = sp.Eq(x - y, b)
eq3 = sp.Eq(y, c)

sol = sp.solve((eq1, eq2, eq3), (x, y, a, b, c))

for k, v in sol.items():
    print(f"{k} = {v}")

a = b + 2*c
x = b + c
y = c


In [33]:
eq4 = sp.Eq(-5*x -4*y + 10*z, a)
eq5 = sp.Eq(-8*x -8*y - 5*z, b)

sol2 = sp.solve((eq4, eq5), (x, y, z, a, b))

for k, v in sol2.items():
    print(f"{k} = {v}")

x = -a + b/2 + 25*z/2
y = a - 5*b/8 - 105*z/8


In [36]:
T = np.array([[1, -2], [-3, 7]])
print(np.linalg.det(T))
O = np.array([[2, 0], [1, -1]])
print(np.linalg.det(O))

0.9999999999999991
-2.0


In [40]:
P = np.array([[1, 5, 2], [2, 0, 1], [1, -1, 1]])
Q = np.array([[5, -2, 4], [0, 1, 5], [1, 2, -8]])
R = np.array([[-7, 0, 0], [3, 11, 0], [9, -8, 4]])
print(np.linalg.det(P))
print(np.linalg.det(Q))
print(np.linalg.det(R))

-7.999999999999998
-103.99999999999999
-308.0000000000001


In [ ]:
S = np.array([[5, -2, 4], [0, 1, 5], [1, 2, -8]])